In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [571]:
class gaussian_nb:
    def __init__(self,x,y):
        self.x=x
        self.y=y
        self.classes,self.freq=np.unique(y,return_counts=True)
        packed=zip(self.classes,self.freq)
        self.priors={}
        self.classes_index={}
        self.subdatasets={}
        for i,f in (packed):
            self.subdatasets.setdefault(i,[])
            self.priors[i]=f/len(self.y)
            self.classes_index[i] = [j for j in range(len(y)) if y[j]==i ]
            for j in self.classes_index[i]:
                self.subdatasets[i].append(x[j])
        
    def calculate(self):
        self.means={}
        self.stds={}
        for i in self.classes:
            self.means.setdefault(i,[])
            self.stds.setdefault(i,[])
            self.means[i]=np.mean(self.subdatasets[i],axis=0)[0]
            self.stds[i]=np.std(self.subdatasets[i],axis=0)[0]
        
    def pred_probs(self,x):
        self.res=[]
        for i in range(len(x)):
            probs = []
            for j in (self.classes):
                probs.append((1/np.sqrt(2*np.pi*self.stds[j]**2)*np.exp(-0.5*
                        ((x[i]-self.means[j])/self.stds[j])**2)).prod()*self.priors[j])
            probs = np.array(probs)
            self.res.append(probs / probs.sum())
        return np.array(self.res)
    
    def predict(self, x):
        
        res = self.pred_probs(x)
        
        return res.argmax(axis=1)
        

In [572]:
x=[[101,90],[110,95],[50,10],[70,10],[60,20],[-1,-2],[-5,-6]]
y=[100,100,999,999,999,222,222]

In [573]:
xy=gaussian_nb(x,y)

In [574]:
xy.calculate()

In [575]:
xy.stds

{100: 4.5, 222: 2.0, 999: 8.16496580927726}

In [576]:
xy.means

{100: 105.5, 222: -3.0, 999: 60.0}

In [577]:
xy.pred_probs(x)

array([[9.99998890e-001, 0.00000000e+000, 1.10962602e-006],
       [1.00000000e+000, 0.00000000e+000, 8.41199078e-012],
       [9.55570190e-123, 7.05308307e-153, 1.00000000e+000],
       [3.13838325e-103, 1.11075224e-289, 1.00000000e+000],
       [9.17947628e-096, 1.18910122e-238, 1.00000000e+000],
       [1.04499355e-246, 1.00000000e+000, 3.84497388e-026],
       [5.64855120e-265, 1.00000000e+000, 5.12700715e-029]])

In [578]:
xy.res

[array([9.99998890e-01, 0.00000000e+00, 1.10962602e-06]),
 array([1.00000000e+00, 0.00000000e+00, 8.41199078e-12]),
 array([9.55570190e-123, 7.05308307e-153, 1.00000000e+000]),
 array([3.13838325e-103, 1.11075224e-289, 1.00000000e+000]),
 array([9.17947628e-096, 1.18910122e-238, 1.00000000e+000]),
 array([1.04499355e-246, 1.00000000e+000, 3.84497388e-026]),
 array([5.64855120e-265, 1.00000000e+000, 5.12700715e-029])]

In [579]:
xy.priors

{100: 0.2857142857142857, 222: 0.2857142857142857, 999: 0.42857142857142855}

In [580]:
len(xy.classes)

3

In [588]:
c=xy.predict([[10,20],[100,250],[-8,0],[-5,-5]])

In [589]:
c

array([2, 2, 1, 1], dtype=int64)

In [590]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x, y)
gnb.predict([[10,20],[100,250],[-8,0],[-5,-5]])

array([999, 999, 222, 222])

In [592]:
#0:100  1:222  2:999